#!/bin/sh
pypath="/home/muhammed.saleem/src/lscsoft/lalsuite/lalapps/src/inspiral/posterior:/home/muhammed.saleem/src/lscsoft/lalsuite/lalapps/src/inspiral/posterior:/home/muhammed.saleem/src/lscsoft/lalsuite/lalstochastic/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalinference/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalpulsar/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalinspiral/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalburst/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalsimulation/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalxml/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalmetaio/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lalframe/python:/home/muhammed.saleem/src/lscsoft/lalsuite/lal/python"
pyscript="/home/muhammed.saleem/src/lscsoft/lalsuite/lalapps/src/inspiral/posterior/lalinference_multi_pipe.py"
PYTHONPATH=`echo "${PYTHONPATH}" | /bin/sed -e "s|${pypath}:||g;"`
PYTHONPATH="${pypath}:${PYTHONPATH}"
export PYTHONPATH
exec /usr/bin/python "${pyscript}" "$@"
exit 1
