
MAKESFTOP=../make_sft_op
MAKESFTPLAIN=../make_sft_plain
MAKESFTSTITCHED=../make_sft_stitched

all:

tests: test1

test1:	test1.op
	$(MAKESFTOP) < test1.op

test2:	test2.plain
	$(MAKESFTPLAIN) < test2.plain
