--Beginning of script 1--   DatabaseDB2LUOW (SEG_LLO) [WARNING***Please do not alter this line]--
-- CONNECT TO SEG_LLO USER XXXX using XXXX;
CREATE TABLESPACE QCASN5 MANAGED BY SYSTEM USING ('QCASN5_TSC');
CREATE TABLE ASN.IBMQREP_CAPPARMS
(
 QMGR VARCHAR(48) NOT NULL,
 REMOTE_SRC_SERVER VARCHAR(18),
 RESTARTQ VARCHAR(48) NOT NULL,
 ADMINQ VARCHAR(48) NOT NULL,
 STARTMODE VARCHAR(6) NOT NULL WITH DEFAULT 'WARMSI',
 MEMORY_LIMIT INTEGER NOT NULL WITH DEFAULT 32,
 COMMIT_INTERVAL INTEGER NOT NULL WITH DEFAULT 500,
 AUTOSTOP CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 MONITOR_INTERVAL INTEGER NOT NULL WITH DEFAULT 300,
 MONITOR_LIMIT INTEGER NOT NULL WITH DEFAULT 10080,
 TRACE_LIMIT INTEGER NOT NULL WITH DEFAULT 10080,
 SIGNAL_LIMIT INTEGER NOT NULL WITH DEFAULT 10080,
 PRUNE_INTERVAL INTEGER NOT NULL WITH DEFAULT 300,
 SLEEP_INTERVAL INTEGER NOT NULL WITH DEFAULT 5000,
 LOGREUSE CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 LOGSTDOUT CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 TERM CHARACTER(1) NOT NULL WITH DEFAULT 'Y',
 CAPTURE_PATH VARCHAR(1040) WITH DEFAULT NULL,
 ARCH_LEVEL CHARACTER(4) NOT NULL WITH DEFAULT '0802',
 CONSTRAINT CC_STARTMODE CHECK(STARTMODE IN ('COLD','WARMSI','WARMSA'
,'WARMNS')),
 CONSTRAINT CC_MEMORY_LIMIT CHECK(MEMORY_LIMIT >= 1 AND MEMORY_LIMIT
 <= 1000),
 CONSTRAINT CC_COMMIT_INTERVAL CHECK(COMMIT_INTERVAL  >= 100 AND
 COMMIT_INTERVAL <= 600000),
 CONSTRAINT CC_AUTOSTOP CHECK(AUTOSTOP IN ('Y','N')),
 CONSTRAINT CC_MON_INTERVAL CHECK(MONITOR_INTERVAL >= 1 AND
 MONITOR_INTERVAL <= 2147483647),
 CONSTRAINT CC_MON_LIMIT CHECK(MONITOR_LIMIT >= 1 AND MONITOR_LIMIT <=
 2147483647),
 CONSTRAINT CC_TRACE_LIMT CHECK(TRACE_LIMIT >= 1 AND TRACE_LIMIT <=
 2147483647),
 CONSTRAINT CC_SIGNAL_LIMIT CHECK(SIGNAL_LIMIT >= 1 AND SIGNAL_LIMIT
 <= 2147483647),
 CONSTRAINT CC_PRUNE_INTERVAL CHECK(PRUNE_INTERVAL >= 1 AND
 PRUNE_INTERVAL <= 2147483647),
 CONSTRAINT CC_LOGREUSE CHECK(LOGREUSE IN ('Y','N')),
 CONSTRAINT CC_LOGSTDOUT CHECK(LOGSTDOUT IN ('Y','N')),
 CONSTRAINT CC_TERM CHECK(TERM IN ('Y','N')),
 CONSTRAINT CC_SLEEP_INTERVAL CHECK(SLEEP_INTERVAL >= 1 AND
 SLEEP_INTERVAL <= 2147483647)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_CAPPARMS
 VOLATILE CARDINALITY;
CREATE UNIQUE INDEX ASN.IX1CQMGRCOL ON ASN.IBMQREP_CAPPARMS
(
 QMGR ASC
);
CREATE TABLE ASN.IBMQREP_SENDQUEUES
(
 PUBQMAPNAME VARCHAR(128) NOT NULL,
 SENDQ VARCHAR(48) NOT NULL,
 RECVQ VARCHAR(48),
 MESSAGE_FORMAT CHARACTER(1) NOT NULL WITH DEFAULT 'C',
 MSG_CONTENT_TYPE CHARACTER(1) NOT NULL WITH DEFAULT 'T',
 STATE CHARACTER(1) NOT NULL WITH DEFAULT 'A',
 STATE_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 STATE_INFO CHARACTER(8),
 ERROR_ACTION CHARACTER(1) NOT NULL WITH DEFAULT 'S',
 HEARTBEAT_INTERVAL INTEGER NOT NULL WITH DEFAULT 60,
 MAX_MESSAGE_SIZE INTEGER NOT NULL WITH DEFAULT 64,
 APPLY_SERVER VARCHAR(18),
 APPLY_ALIAS VARCHAR(8),
 APPLY_SCHEMA VARCHAR(128),
 DESCRIPTION VARCHAR(254),
 PRIMARY KEY(SENDQ),
 CONSTRAINT CC_MSG_FORMAT CHECK(MESSAGE_FORMAT IN ('X','C', 'J')),
 CONSTRAINT CC_MSG_CONT_TYPE CHECK(MSG_CONTENT_TYPE IN ('T','R')),
 CONSTRAINT CC_SENDQ_STATE CHECK(STATE IN ('A','I')),
 CONSTRAINT CC_QERRORACTION CHECK(ERROR_ACTION IN ('I','S')),
 CONSTRAINT CC_HTBEAT_INTERVAL CHECK(HEARTBEAT_INTERVAL >= 0 AND
 HEARTBEAT_INTERVAL <= 32767)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_SENDQUEUES
 VOLATILE CARDINALITY;
CREATE UNIQUE INDEX ASN.IX1PUBMAPCOL ON ASN.IBMQREP_SENDQUEUES
(
 PUBQMAPNAME ASC
);
CREATE TABLE ASN.IBMQREP_SUBS
(
 SUBNAME VARCHAR(132) NOT NULL,
 SOURCE_OWNER VARCHAR(128) NOT NULL,
 SOURCE_NAME VARCHAR(128) NOT NULL,
 TARGET_SERVER VARCHAR(18),
 TARGET_ALIAS VARCHAR(8),
 TARGET_OWNER VARCHAR(128),
 TARGET_NAME VARCHAR(128),
 TARGET_TYPE INTEGER,
 APPLY_SCHEMA VARCHAR(128),
 SENDQ VARCHAR(48) NOT NULL,
 SEARCH_CONDITION VARCHAR(2048) WITH DEFAULT NULL,
 SUB_ID INTEGER WITH DEFAULT NULL,
 SUBTYPE CHARACTER(1) NOT NULL WITH DEFAULT 'U',
 ALL_CHANGED_ROWS CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 BEFORE_VALUES CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 CHANGED_COLS_ONLY CHARACTER(1) NOT NULL WITH DEFAULT 'Y',
 HAS_LOADPHASE CHARACTER(1) NOT NULL WITH DEFAULT 'I',
 STATE CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 STATE_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 STATE_INFO CHARACTER(8),
 STATE_TRANSITION VARCHAR(256) FOR BIT DATA,
 SUBGROUP VARCHAR(30) WITH DEFAULT NULL,
 SOURCE_NODE SMALLINT NOT NULL WITH DEFAULT 0,
 TARGET_NODE SMALLINT NOT NULL WITH DEFAULT 0,
 GROUP_MEMBERS CHARACTER(254) FOR BIT DATA WITH DEFAULT NULL,
 OPTIONS_FLAG CHARACTER(4) NOT NULL WITH DEFAULT 'NNNN',
 SUPPRESS_DELETES CHARACTER(1) NOT NULL WITH DEFAULT 'N',
 DESCRIPTION VARCHAR(200),
 TOPIC VARCHAR(256),
 PRIMARY KEY(SUBNAME),
 CONSTRAINT FKSENDQ FOREIGN KEY(SENDQ) REFERENCES
 ASN.IBMQREP_SENDQUEUES(SENDQ),
 CONSTRAINT CC_SUBTYPE CHECK(SUBTYPE IN ('U','B','P')),
 CONSTRAINT CC_ALL_CHGD_ROWS CHECK(ALL_CHANGED_ROWS IN ('Y','N')),
 CONSTRAINT CC_BEFORE_VALUES CHECK(BEFORE_VALUES IN ('Y','N')),
 CONSTRAINT CC_CHGD_COLS_ONLY CHECK(CHANGED_COLS_ONLY IN ('Y','N')),
 CONSTRAINT CC_HAS_LOADPHASE CHECK(HAS_LOADPHASE IN ('N','I','E')),
 CONSTRAINT CC_SUBS_STATE CHECK(STATE IN ('L','A','I','T','G','N')),
 CONSTRAINT CC_SUPPRESS_DELS CHECK(SUPPRESS_DELETES IN ('Y','N'))
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_SUBS
 VOLATILE CARDINALITY;
CREATE TABLE ASN.IBMQREP_SRC_COLS
(
 SUBNAME VARCHAR(132) NOT NULL,
 SRC_COLNAME VARCHAR(128) NOT NULL,
 IS_KEY SMALLINT NOT NULL WITH DEFAULT 0,
 PRIMARY KEY(SUBNAME, SRC_COLNAME),
 CONSTRAINT FKSUBS FOREIGN KEY(SUBNAME) REFERENCES ASN.IBMQREP_SUBS
(SUBNAME)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_SRC_COLS
 VOLATILE CARDINALITY;
CREATE TABLE ASN.IBMQREP_SRCH_COND
(
 ASNQREQD INTEGER
)
 IN QCASN5;
CREATE TABLE ASN.IBMQREP_SIGNAL
(
 SIGNAL_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 SIGNAL_TYPE VARCHAR(30) NOT NULL,
 SIGNAL_SUBTYPE VARCHAR(30),
 SIGNAL_INPUT_IN VARCHAR(500),
 SIGNAL_STATE CHARACTER(1) NOT NULL WITH DEFAULT 'P',
 SIGNAL_LSN CHARACTER(10) FOR BIT DATA,
 PRIMARY KEY(SIGNAL_TIME),
 CONSTRAINT CC_SIGNAL_TYPE CHECK(SIGNAL_TYPE IN ('CMD','USER')),
 CONSTRAINT CC_SIGNAL_STATE CHECK(SIGNAL_STATE IN ('P','R','C','F'))
)
 DATA CAPTURE CHANGES
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_SIGNAL
 VOLATILE CARDINALITY;
CREATE TABLE ASN.IBMQREP_CAPTRACE
(
 OPERATION CHARACTER(8) NOT NULL,
 TRACE_TIME TIMESTAMP NOT NULL,
 DESCRIPTION VARCHAR(1024) NOT NULL
)
 IN QCASN5;
CREATE TABLE ASN.IBMQREP_CAPMON
(
 MONITOR_TIME TIMESTAMP NOT NULL,
 CURRENT_LOG_TIME TIMESTAMP NOT NULL,
 CAPTURE_IDLE INTEGER NOT NULL,
 CURRENT_MEMORY INTEGER NOT NULL,
 ROWS_PROCESSED INTEGER NOT NULL,
 TRANS_SKIPPED INTEGER NOT NULL,
 TRANS_PROCESSED INTEGER NOT NULL,
 TRANS_SPILLED INTEGER NOT NULL,
 MAX_TRANS_SIZE INTEGER NOT NULL,
 QUEUES_IN_ERROR INTEGER NOT NULL,
 RESTART_SEQ CHARACTER(10) FOR BIT DATA NOT NULL,
 CURRENT_SEQ CHARACTER(10) FOR BIT DATA NOT NULL,
 PRIMARY KEY(MONITOR_TIME)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_CAPMON
 VOLATILE CARDINALITY;
CREATE TABLE ASN.IBMQREP_CAPQMON
(
 MONITOR_TIME TIMESTAMP NOT NULL,
 SENDQ VARCHAR(48) NOT NULL,
 ROWS_PUBLISHED INTEGER NOT NULL,
 TRANS_PUBLISHED INTEGER NOT NULL,
 CHG_ROWS_SKIPPED INTEGER NOT NULL,
 DELROWS_SUPPRESSED INTEGER NOT NULL,
 ROWS_SKIPPED INTEGER NOT NULL,
 PRIMARY KEY(MONITOR_TIME, SENDQ)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_CAPQMON
 VOLATILE CARDINALITY;
CREATE TABLE ASN.IBMQREP_CAPENQ
(
 LOCKNAME INTEGER
)
 IN QCASN5;
CREATE TABLE ASN.IBMQREP_ADMINMSG
(
 MQMSGID CHARACTER(24) FOR BIT DATA NOT NULL,
 MSG_TIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 PRIMARY KEY(MQMSGID)
)
 IN QCASN5;
ALTER TABLE ASN.IBMQREP_ADMINMSG
 VOLATILE CARDINALITY;
INSERT INTO ASN.IBMQREP_CAPPARMS
 (qmgr, restartq, adminq, startmode, memory_limit, commit_interval,
 autostop, monitor_interval, monitor_limit, trace_limit, signal_limit,
 prune_interval, sleep_interval, logreuse, logstdout, term, arch_level)
 VALUES
 ('QM2', 'ASN.QM2.RESTARTQ', 'ASN.QM2.ADMINQ', 'WARMSI', 32, 500, 'N',
 300, 10080, 10080, 10080, 300, 5000, 'N', 'N', 'Y', '0802');
-- COMMIT;