# $Id$
#
# Copyright (C) 2008  Kipp C. Cannon
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#


"""
Code to assist in reading and writing LAL time- and frequency series data
encoded in LIGO Light-Weight XML format.  The format recognized by the code
in this module is compatible with the format used by the DMT to store time-
and frequency-series data in XML files, and is the same as generated by the
array-related functions in LAL's XML I/O code.
"""


from glue.ligolw import ligolw
from glue.ligolw import param
from pylal.xlal.datatypes.lalunit import LALUnit
from pylal.xlal.datatypes.ligotimegps import LIGOTimeGPS
from pylal.xlal.datatypes.real8frequencyseries import REAL8FrequencySeries
from pylal.xlal.datatypes.real8timeseries import REAL8TimeSeries


__author__ = "Kipp Cannon <kipp.cannon@ligo.org>"
__version__ = "$Revision$"[11:-2]
__date__ = "$Date$"[7:-2]


#
# =============================================================================
#
#                                     Body
#
# =============================================================================
#


def parse_COMPLEX16FrequencySeries(elem):
	t, = elem.getElementsByTagName(ligolw.Time.tagName)
	a, = elem.getElementsByTagName(ligolw.Array.tagName)
	dims = a.getElementsByTagName(ligolw.Dim.tagName)
	return COMPLEX16FrequencySeries(
		name = a.getAttribute(u"Name"),
		epoch = LIGOTimeGPS(t.pcdata),
		f0 = param.get_pyvalue(elem, u"f0"),
		deltaF = float(dims[0].getAttribute(u"Scale")),
		sampleUnits = LALUnit(a.getAttribute(u"Unit")),
		data = a.array[1] + 1j * a.array[2]
	)


def parse_REAL8FrequencySeries(elem):
	t, = elem.getElementsByTagName(ligolw.Time.tagName)
	a, = elem.getElementsByTagName(ligolw.Array.tagName)
	dims = a.getElementsByTagName(ligolw.Dim.tagName)
	return REAL8FrequencySeries(
		name = a.getAttribute(u"Name"),
		epoch = LIGOTimeGPS(t.pcdata),
		f0 = param.get_pyvalue(elem, u"f0"),
		deltaF = float(dims[0].getAttribute(u"Scale")),
		sampleUnits = LALUnit(a.getAttribute(u"Unit")),
		data = a.array[1]
	)


def parse_REAL8TimeSeries(elem):
	t, = elem.getElementsByTagName(ligolw.Time.tagName)
	a, = elem.getElementsByTagName(ligolw.Array.tagName)
	dims = a.getElementsByTagName(ligolw.Dim.tagName)
	return REAL8TimeSeries(
		name = a.getAttribute(u"Name"),
		epoch = LIGOTimeGPS(t.pcdata),
		f0 = param.get_pyvalue(elem, u"f0"),
		deltaT = float(dims[0].getAttribute(u"Scale")),
		sampleUnits = LALUnit(a.getAttribute(u"Unit"))
		data = a.array[1]
	)
