/*
  File autogenerated by gengetopt version 2.11
  generated with the following command:
  gengetopt --conf-parser 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "getopt.h"

#include "cmdline.h"

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Purpose:\n"
  "  Powerflux analysis program\n"
  "\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("\n");
  printf("  -h, --help                       Print help and exit\n");
  printf("  -V, --version                    Print version and exit\n");
  printf("  -c, --config=STRING              configuration file (in gengetopt format) to \n                                     pass parameters\n");
  printf("      --sky-grid=STRING            sky grid type (arcsin, plain_rectangular, \n                                     sin_theta)  (default=`sin_theta')\n");
  printf("      --skymap-orientation=STRING  orientation of produced skymaps: \n                                     equatorial, ecliptic, band_axis  (default=\n                                     `equatorial')\n");
  printf("      --fine-factor=INT            make fine grid this times finer  (default=\n                                     `7')\n");
  printf("      --resolution-ratio=DOUBLE    ratio that determines the coarsness of the \n                                     grid  (default=`1.0')\n");
  printf("      --small-weight-ratio=DOUBLE  ratio that determines which weight is too \n                                     small to include in max statistics  \n                                     (default=`0.2')\n");
  printf("  -i, --input=STRING               path to input files (power or SFT)\n");
  printf("      --input-munch=STRING         how to derive SFT name from --input (highly \n                                     arcane)  (default=`%s%ld')\n");
  printf("      --input-format=STRING        format of input files (GEO, SFT, Power)  \n                                     (default=`GEO')\n");
  printf("      --segments-file=STRING       file with list of segments to process - \n                                     this allows subsetting of full SFT set\n");
  printf("      --veto-segments-file=STRING  file with list of segments *NOT* to process \n                                     - this allows subsetting of full SFT set\n");
  printf("  -o, --output=STRING              output directory\n");
  printf("      --ephemeris-path=STRING      path to detresponse program from lalapps\n");
  printf("      --earth-ephemeris=STRING     Earth ephemeris file, overrides \n                                     ephemeris-path argument\n");
  printf("      --sun-ephemeris=STRING       Sun ephemeris file, overrides \n                                     ephemeris-path argument\n");
  printf("  -f, --first-bin=INT              first frequency bin in the band to be \n                                     analyzed\n");
  printf("  -n, --nbins=INT                  number of frequency bins to analyze  \n                                     (default=`501')\n");
  printf("      --side-cut=INT               number of bins to cut from each side due to \n                                     corruption from doppler shifts\n");
  printf("  -d, --detector=STRING            detector location (i.e. LHO or LLO), passed \n                                     to detresponse\n");
  printf("      --spindown=DOUBLE            compensate for pulsar spindown during run \n                                     (fdot)  (default=`0')\n");
  printf("      --orientation=DOUBLE         additional orientation phase, specifying \n                                     0.7853 will turn plus into cross  \n                                     (default=`0')\n");
  printf("      --npolarizations=INT         number of linear polarizations to profile, \n                                     distributed uniformly between plus and \n                                     cross  (default=`3')\n");
  printf("      --no-demodulation=INT        do not perform demodulation stage, analyze \n                                     background only  (default=`0')\n");
  printf("      --no-decomposition=INT       do not perform noise decomposition stage, \n                                     output simple statistics only  (default=\n                                     `0')\n");
  printf("      --no-am-response=INT         force AM_response() function to return 1.0 \n                                     irrespective of the arguments  (default=\n                                     `0')\n");
  printf("      --three-bins=INT             average 3 neighbouring bins to broaden \n                                     Doppler curves  (default=`0')\n");
  printf("      --do-cutoff=INT              neglect contribution from SFT with high \n                                     effective noise level  (default=`1')\n");
  printf("      --filter-lines=INT           perform detection of lines in background \n                                     noise and veto corresponding frequency \n                                     bins  (default=`1')\n");
  printf("      --nbands=INT                 split sky in this many bands for logging \n                                     maximum upper limits  (default=`9')\n");
  printf("      --band-axis=STRING           which band axis to use for splitting sky \n                                     into bands (perpendicular to band axis) \n                                     (possible values: equatorial, auto, \n                                     explicit(float,float,float)  (default=\n                                     `auto')\n");
  printf("      --fake-ra=DOUBLE             RA of fake signal to inject  (default=\n                                     `3.14')\n");
  printf("      --fake-dec=DOUBLE            DEC of fake signal to inject  (default=\n                                     `0.0')\n");
  printf("      --fake-orientation=DOUBLE    orientation of fake signal to inject  \n                                     (default=`0.0')\n");
  printf("      --fake-spindown=DOUBLE       spindown of fake signal to inject  (default=\n                                     `0.0')\n");
  printf("      --fake-strain=DOUBLE         amplitude of fake signal to inject  \n                                     (default=`1e-23')\n");
  printf("      --fake-freq=DOUBLE           frequency of fake signal to inject\n");
  printf("      --write-dat=STRING           regular expression describing which *.dat \n                                     files to write  (default=`.*')\n");
  printf("      --write-png=STRING           regular expression describing which *.png \n                                     files to write  (default=`.*')\n");
  printf("      --focus-ra=DOUBLE            focus computation on a circular area with \n                                     center at this RA\n");
  printf("      --focus-dec=DOUBLE           focus computation on a circular area with \n                                     center at this DEC\n");
  printf("      --focus-radius=DOUBLE        focus computation on a circular area with \n                                     this radius\n");
}


static char *gengetopt_strdup (const char *s);

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->config_given = 0 ;
  args_info->sky_grid_given = 0 ;
  args_info->skymap_orientation_given = 0 ;
  args_info->fine_factor_given = 0 ;
  args_info->resolution_ratio_given = 0 ;
  args_info->small_weight_ratio_given = 0 ;
  args_info->input_given = 0 ;
  args_info->input_munch_given = 0 ;
  args_info->input_format_given = 0 ;
  args_info->segments_file_given = 0 ;
  args_info->veto_segments_file_given = 0 ;
  args_info->output_given = 0 ;
  args_info->ephemeris_path_given = 0 ;
  args_info->earth_ephemeris_given = 0 ;
  args_info->sun_ephemeris_given = 0 ;
  args_info->first_bin_given = 0 ;
  args_info->nbins_given = 0 ;
  args_info->side_cut_given = 0 ;
  args_info->detector_given = 0 ;
  args_info->spindown_given = 0 ;
  args_info->orientation_given = 0 ;
  args_info->npolarizations_given = 0 ;
  args_info->no_demodulation_given = 0 ;
  args_info->no_decomposition_given = 0 ;
  args_info->no_am_response_given = 0 ;
  args_info->three_bins_given = 0 ;
  args_info->do_cutoff_given = 0 ;
  args_info->filter_lines_given = 0 ;
  args_info->nbands_given = 0 ;
  args_info->band_axis_given = 0 ;
  args_info->fake_ra_given = 0 ;
  args_info->fake_dec_given = 0 ;
  args_info->fake_orientation_given = 0 ;
  args_info->fake_spindown_given = 0 ;
  args_info->fake_strain_given = 0 ;
  args_info->fake_freq_given = 0 ;
  args_info->write_dat_given = 0 ;
  args_info->write_png_given = 0 ;
  args_info->focus_ra_given = 0 ;
  args_info->focus_dec_given = 0 ;
  args_info->focus_radius_given = 0 ;
#define clear_args() { \
  args_info->config_arg = NULL; \
  args_info->sky_grid_arg = gengetopt_strdup("sin_theta") ;\
  args_info->skymap_orientation_arg = gengetopt_strdup("equatorial") ;\
  args_info->fine_factor_arg = 7 ;\
  args_info->resolution_ratio_arg = 1.0 ;\
  args_info->small_weight_ratio_arg = 0.2 ;\
  args_info->input_arg = NULL; \
  args_info->input_munch_arg = gengetopt_strdup("%s%ld") ;\
  args_info->input_format_arg = gengetopt_strdup("GEO") ;\
  args_info->segments_file_arg = NULL; \
  args_info->veto_segments_file_arg = NULL; \
  args_info->output_arg = NULL; \
  args_info->ephemeris_path_arg = NULL; \
  args_info->earth_ephemeris_arg = NULL; \
  args_info->sun_ephemeris_arg = NULL; \
  args_info->nbins_arg = 501 ;\
  args_info->detector_arg = NULL; \
  args_info->spindown_arg = 0 ;\
  args_info->orientation_arg = 0 ;\
  args_info->npolarizations_arg = 3 ;\
  args_info->no_demodulation_arg = 0 ;\
  args_info->no_decomposition_arg = 0 ;\
  args_info->no_am_response_arg = 0 ;\
  args_info->three_bins_arg = 0 ;\
  args_info->do_cutoff_arg = 1 ;\
  args_info->filter_lines_arg = 1 ;\
  args_info->nbands_arg = 9 ;\
  args_info->band_axis_arg = gengetopt_strdup("auto") ;\
  args_info->fake_ra_arg = 3.14 ;\
  args_info->fake_dec_arg = 0.0 ;\
  args_info->fake_orientation_arg = 0.0 ;\
  args_info->fake_spindown_arg = 0.0 ;\
  args_info->fake_strain_arg = 1e-23 ;\
  args_info->write_dat_arg = gengetopt_strdup(".*") ;\
  args_info->write_png_arg = gengetopt_strdup(".*") ;\
}

  clear_args();

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "config",	1, NULL, 'c' },
        { "sky-grid",	1, NULL, 0 },
        { "skymap-orientation",	1, NULL, 0 },
        { "fine-factor",	1, NULL, 0 },
        { "resolution-ratio",	1, NULL, 0 },
        { "small-weight-ratio",	1, NULL, 0 },
        { "input",	1, NULL, 'i' },
        { "input-munch",	1, NULL, 0 },
        { "input-format",	1, NULL, 0 },
        { "segments-file",	1, NULL, 0 },
        { "veto-segments-file",	1, NULL, 0 },
        { "output",	1, NULL, 'o' },
        { "ephemeris-path",	1, NULL, 0 },
        { "earth-ephemeris",	1, NULL, 0 },
        { "sun-ephemeris",	1, NULL, 0 },
        { "first-bin",	1, NULL, 'f' },
        { "nbins",	1, NULL, 'n' },
        { "side-cut",	1, NULL, 0 },
        { "detector",	1, NULL, 'd' },
        { "spindown",	1, NULL, 0 },
        { "orientation",	1, NULL, 0 },
        { "npolarizations",	1, NULL, 0 },
        { "no-demodulation",	1, NULL, 0 },
        { "no-decomposition",	1, NULL, 0 },
        { "no-am-response",	1, NULL, 0 },
        { "three-bins",	1, NULL, 0 },
        { "do-cutoff",	1, NULL, 0 },
        { "filter-lines",	1, NULL, 0 },
        { "nbands",	1, NULL, 0 },
        { "band-axis",	1, NULL, 0 },
        { "fake-ra",	1, NULL, 0 },
        { "fake-dec",	1, NULL, 0 },
        { "fake-orientation",	1, NULL, 0 },
        { "fake-spindown",	1, NULL, 0 },
        { "fake-strain",	1, NULL, 0 },
        { "fake-freq",	1, NULL, 0 },
        { "write-dat",	1, NULL, 0 },
        { "write-png",	1, NULL, 0 },
        { "focus-ra",	1, NULL, 0 },
        { "focus-dec",	1, NULL, 0 },
        { "focus-radius",	1, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVc:i:o:f:n:d:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'c':	/* configuration file (in gengetopt format) to pass parameters.  */
          if (args_info->config_given)
            {
              fprintf (stderr, "%s: `--config' (`-c') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->config_given = 1;
          args_info->config_arg = gengetopt_strdup (optarg);
          break;

        case 'i':	/* path to input files (power or SFT).  */
          if (args_info->input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->input_given = 1;
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* output directory.  */
          if (args_info->output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->output_given = 1;
          args_info->output_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* first frequency bin in the band to be analyzed.  */
          if (args_info->first_bin_given)
            {
              fprintf (stderr, "%s: `--first-bin' (`-f') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->first_bin_given = 1;
          args_info->first_bin_arg = strtol (optarg,&stop_char,0);
          break;

        case 'n':	/* number of frequency bins to analyze.  */
          if (args_info->nbins_given)
            {
              fprintf (stderr, "%s: `--nbins' (`-n') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->nbins_given = 1;
          args_info->nbins_arg = strtol (optarg,&stop_char,0);
          break;

        case 'd':	/* detector location (i.e. LHO or LLO), passed to detresponse.  */
          if (args_info->detector_given)
            {
              fprintf (stderr, "%s: `--detector' (`-d') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->detector_given = 1;
          args_info->detector_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
          /* sky grid type (arcsin, plain_rectangular, sin_theta).  */
          if (strcmp (long_options[option_index].name, "sky-grid") == 0)
          {
            if (args_info->sky_grid_given)
              {
                fprintf (stderr, "%s: `--sky-grid' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->sky_grid_given = 1;
            if (args_info->sky_grid_arg)
              free (args_info->sky_grid_arg); /* free default string */
            args_info->sky_grid_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* orientation of produced skymaps: equatorial, ecliptic, band_axis.  */
          else if (strcmp (long_options[option_index].name, "skymap-orientation") == 0)
          {
            if (args_info->skymap_orientation_given)
              {
                fprintf (stderr, "%s: `--skymap-orientation' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->skymap_orientation_given = 1;
            if (args_info->skymap_orientation_arg)
              free (args_info->skymap_orientation_arg); /* free default string */
            args_info->skymap_orientation_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* make fine grid this times finer.  */
          else if (strcmp (long_options[option_index].name, "fine-factor") == 0)
          {
            if (args_info->fine_factor_given)
              {
                fprintf (stderr, "%s: `--fine-factor' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fine_factor_given = 1;
            args_info->fine_factor_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* ratio that determines the coarsness of the grid.  */
          else if (strcmp (long_options[option_index].name, "resolution-ratio") == 0)
          {
            if (args_info->resolution_ratio_given)
              {
                fprintf (stderr, "%s: `--resolution-ratio' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->resolution_ratio_given = 1;
            args_info->resolution_ratio_arg = strtod (optarg, NULL);
            break;
          }
          
          /* ratio that determines which weight is too small to include in max statistics.  */
          else if (strcmp (long_options[option_index].name, "small-weight-ratio") == 0)
          {
            if (args_info->small_weight_ratio_given)
              {
                fprintf (stderr, "%s: `--small-weight-ratio' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->small_weight_ratio_given = 1;
            args_info->small_weight_ratio_arg = strtod (optarg, NULL);
            break;
          }
          
          /* how to derive SFT name from --input (highly arcane).  */
          else if (strcmp (long_options[option_index].name, "input-munch") == 0)
          {
            if (args_info->input_munch_given)
              {
                fprintf (stderr, "%s: `--input-munch' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->input_munch_given = 1;
            if (args_info->input_munch_arg)
              free (args_info->input_munch_arg); /* free default string */
            args_info->input_munch_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* format of input files (GEO, SFT, Power).  */
          else if (strcmp (long_options[option_index].name, "input-format") == 0)
          {
            if (args_info->input_format_given)
              {
                fprintf (stderr, "%s: `--input-format' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->input_format_given = 1;
            if (args_info->input_format_arg)
              free (args_info->input_format_arg); /* free default string */
            args_info->input_format_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* file with list of segments to process - this allows subsetting of full SFT set.  */
          else if (strcmp (long_options[option_index].name, "segments-file") == 0)
          {
            if (args_info->segments_file_given)
              {
                fprintf (stderr, "%s: `--segments-file' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->segments_file_given = 1;
            args_info->segments_file_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* file with list of segments *NOT* to process - this allows subsetting of full SFT set.  */
          else if (strcmp (long_options[option_index].name, "veto-segments-file") == 0)
          {
            if (args_info->veto_segments_file_given)
              {
                fprintf (stderr, "%s: `--veto-segments-file' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->veto_segments_file_given = 1;
            args_info->veto_segments_file_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* path to detresponse program from lalapps.  */
          else if (strcmp (long_options[option_index].name, "ephemeris-path") == 0)
          {
            if (args_info->ephemeris_path_given)
              {
                fprintf (stderr, "%s: `--ephemeris-path' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->ephemeris_path_given = 1;
            args_info->ephemeris_path_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* Earth ephemeris file, overrides ephemeris-path argument.  */
          else if (strcmp (long_options[option_index].name, "earth-ephemeris") == 0)
          {
            if (args_info->earth_ephemeris_given)
              {
                fprintf (stderr, "%s: `--earth-ephemeris' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->earth_ephemeris_given = 1;
            args_info->earth_ephemeris_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* Sun ephemeris file, overrides ephemeris-path argument.  */
          else if (strcmp (long_options[option_index].name, "sun-ephemeris") == 0)
          {
            if (args_info->sun_ephemeris_given)
              {
                fprintf (stderr, "%s: `--sun-ephemeris' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->sun_ephemeris_given = 1;
            args_info->sun_ephemeris_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* number of bins to cut from each side due to corruption from doppler shifts.  */
          else if (strcmp (long_options[option_index].name, "side-cut") == 0)
          {
            if (args_info->side_cut_given)
              {
                fprintf (stderr, "%s: `--side-cut' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->side_cut_given = 1;
            args_info->side_cut_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* compensate for pulsar spindown during run (fdot).  */
          else if (strcmp (long_options[option_index].name, "spindown") == 0)
          {
            if (args_info->spindown_given)
              {
                fprintf (stderr, "%s: `--spindown' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->spindown_given = 1;
            args_info->spindown_arg = strtod (optarg, NULL);
            break;
          }
          
          /* additional orientation phase, specifying 0.7853 will turn plus into cross.  */
          else if (strcmp (long_options[option_index].name, "orientation") == 0)
          {
            if (args_info->orientation_given)
              {
                fprintf (stderr, "%s: `--orientation' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->orientation_given = 1;
            args_info->orientation_arg = strtod (optarg, NULL);
            break;
          }
          
          /* number of linear polarizations to profile, distributed uniformly between plus and cross.  */
          else if (strcmp (long_options[option_index].name, "npolarizations") == 0)
          {
            if (args_info->npolarizations_given)
              {
                fprintf (stderr, "%s: `--npolarizations' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->npolarizations_given = 1;
            args_info->npolarizations_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* do not perform demodulation stage, analyze background only.  */
          else if (strcmp (long_options[option_index].name, "no-demodulation") == 0)
          {
            if (args_info->no_demodulation_given)
              {
                fprintf (stderr, "%s: `--no-demodulation' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->no_demodulation_given = 1;
            args_info->no_demodulation_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* do not perform noise decomposition stage, output simple statistics only.  */
          else if (strcmp (long_options[option_index].name, "no-decomposition") == 0)
          {
            if (args_info->no_decomposition_given)
              {
                fprintf (stderr, "%s: `--no-decomposition' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->no_decomposition_given = 1;
            args_info->no_decomposition_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* force AM_response() function to return 1.0 irrespective of the arguments.  */
          else if (strcmp (long_options[option_index].name, "no-am-response") == 0)
          {
            if (args_info->no_am_response_given)
              {
                fprintf (stderr, "%s: `--no-am-response' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->no_am_response_given = 1;
            args_info->no_am_response_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* average 3 neighbouring bins to broaden Doppler curves.  */
          else if (strcmp (long_options[option_index].name, "three-bins") == 0)
          {
            if (args_info->three_bins_given)
              {
                fprintf (stderr, "%s: `--three-bins' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->three_bins_given = 1;
            args_info->three_bins_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* neglect contribution from SFT with high effective noise level.  */
          else if (strcmp (long_options[option_index].name, "do-cutoff") == 0)
          {
            if (args_info->do_cutoff_given)
              {
                fprintf (stderr, "%s: `--do-cutoff' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->do_cutoff_given = 1;
            args_info->do_cutoff_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* perform detection of lines in background noise and veto corresponding frequency bins.  */
          else if (strcmp (long_options[option_index].name, "filter-lines") == 0)
          {
            if (args_info->filter_lines_given)
              {
                fprintf (stderr, "%s: `--filter-lines' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->filter_lines_given = 1;
            args_info->filter_lines_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* split sky in this many bands for logging maximum upper limits.  */
          else if (strcmp (long_options[option_index].name, "nbands") == 0)
          {
            if (args_info->nbands_given)
              {
                fprintf (stderr, "%s: `--nbands' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->nbands_given = 1;
            args_info->nbands_arg = strtol (optarg,&stop_char,0);
            break;
          }
          
          /* which band axis to use for splitting sky into bands (perpendicular to band axis) (possible values: equatorial, auto, explicit(float,float,float).  */
          else if (strcmp (long_options[option_index].name, "band-axis") == 0)
          {
            if (args_info->band_axis_given)
              {
                fprintf (stderr, "%s: `--band-axis' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->band_axis_given = 1;
            if (args_info->band_axis_arg)
              free (args_info->band_axis_arg); /* free default string */
            args_info->band_axis_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* RA of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-ra") == 0)
          {
            if (args_info->fake_ra_given)
              {
                fprintf (stderr, "%s: `--fake-ra' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_ra_given = 1;
            args_info->fake_ra_arg = strtod (optarg, NULL);
            break;
          }
          
          /* DEC of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-dec") == 0)
          {
            if (args_info->fake_dec_given)
              {
                fprintf (stderr, "%s: `--fake-dec' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_dec_given = 1;
            args_info->fake_dec_arg = strtod (optarg, NULL);
            break;
          }
          
          /* orientation of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-orientation") == 0)
          {
            if (args_info->fake_orientation_given)
              {
                fprintf (stderr, "%s: `--fake-orientation' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_orientation_given = 1;
            args_info->fake_orientation_arg = strtod (optarg, NULL);
            break;
          }
          
          /* spindown of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-spindown") == 0)
          {
            if (args_info->fake_spindown_given)
              {
                fprintf (stderr, "%s: `--fake-spindown' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_spindown_given = 1;
            args_info->fake_spindown_arg = strtod (optarg, NULL);
            break;
          }
          
          /* amplitude of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-strain") == 0)
          {
            if (args_info->fake_strain_given)
              {
                fprintf (stderr, "%s: `--fake-strain' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_strain_given = 1;
            args_info->fake_strain_arg = strtod (optarg, NULL);
            break;
          }
          
          /* frequency of fake signal to inject.  */
          else if (strcmp (long_options[option_index].name, "fake-freq") == 0)
          {
            if (args_info->fake_freq_given)
              {
                fprintf (stderr, "%s: `--fake-freq' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->fake_freq_given = 1;
            args_info->fake_freq_arg = strtod (optarg, NULL);
            break;
          }
          
          /* regular expression describing which *.dat files to write.  */
          else if (strcmp (long_options[option_index].name, "write-dat") == 0)
          {
            if (args_info->write_dat_given)
              {
                fprintf (stderr, "%s: `--write-dat' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->write_dat_given = 1;
            if (args_info->write_dat_arg)
              free (args_info->write_dat_arg); /* free default string */
            args_info->write_dat_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* regular expression describing which *.png files to write.  */
          else if (strcmp (long_options[option_index].name, "write-png") == 0)
          {
            if (args_info->write_png_given)
              {
                fprintf (stderr, "%s: `--write-png' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->write_png_given = 1;
            if (args_info->write_png_arg)
              free (args_info->write_png_arg); /* free default string */
            args_info->write_png_arg = gengetopt_strdup (optarg);
            break;
          }
          
          /* focus computation on a circular area with center at this RA.  */
          else if (strcmp (long_options[option_index].name, "focus-ra") == 0)
          {
            if (args_info->focus_ra_given)
              {
                fprintf (stderr, "%s: `--focus-ra' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->focus_ra_given = 1;
            args_info->focus_ra_arg = strtod (optarg, NULL);
            break;
          }
          
          /* focus computation on a circular area with center at this DEC.  */
          else if (strcmp (long_options[option_index].name, "focus-dec") == 0)
          {
            if (args_info->focus_dec_given)
              {
                fprintf (stderr, "%s: `--focus-dec' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->focus_dec_given = 1;
            args_info->focus_dec_arg = strtod (optarg, NULL);
            break;
          }
          
          /* focus computation on a circular area with this radius.  */
          else if (strcmp (long_options[option_index].name, "focus-radius") == 0)
          {
            if (args_info->focus_radius_given)
              {
                fprintf (stderr, "%s: `--focus-radius' option given more than once\n", CMDLINE_PARSER_PACKAGE);
                clear_args ();
                exit (EXIT_FAILURE);
              }
            args_info->focus_radius_given = 1;
            args_info->focus_radius_arg = strtod (optarg, NULL);
            break;
          }
          

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (EXIT_FAILURE);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", CMDLINE_PARSER_PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */


  if ( missing_required_options )
    exit (EXIT_FAILURE);

  return 0;
}

#define CONFIGPARSERBUFSIZE 1024

int
cmdline_parser_configfile (char * const filename, struct gengetopt_args_info *args_info, int override)
{
  FILE* file;
  char linebuf[CONFIGPARSERBUFSIZE];
  int line_num = 0;
  int len;
  int fnum;
  char fopt[CONFIGPARSERBUFSIZE], farg[CONFIGPARSERBUFSIZE];
  char *stop_char;
  char *str_index, *str_index2;
  int next_token;

  if ((file = fopen(filename, "r")) == NULL)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      exit (EXIT_FAILURE);
    }

  while ((fgets(linebuf, CONFIGPARSERBUFSIZE, file)) != NULL)
    {
      ++line_num;
      len = strlen(linebuf);
      if (len == CONFIGPARSERBUFSIZE-1)
        {
          fprintf (stderr, "%s: Line longer than %d characters found in configuration file '%s'\n",
                   CMDLINE_PARSER_PACKAGE, CONFIGPARSERBUFSIZE, filename);
          exit (EXIT_FAILURE);
        }

      if (linebuf[0] == '#')
        continue; /* Line was a comment */

      /* read the option */
      fnum = sscanf (linebuf, "%s", fopt);

      if (fnum < 0)
        continue; /* blank line */

      next_token = strlen (fopt);
      str_index = strchr (&linebuf[next_token], '\"');
      if (str_index)
        {
          str_index2 = strchr (str_index + 1, '\"');
          if (! str_index2)
            {
              fprintf 
                (stderr, 
                 "%s: unterminated string in configuration file '%s'\n",
                 CMDLINE_PARSER_PACKAGE, filename);
              exit (EXIT_FAILURE);
            }

          strncpy (farg, str_index + 1, str_index2 - str_index - 1);
          farg[str_index2 - str_index - 1]='\0';
          ++fnum;
        }
      else
        if (sscanf (&linebuf[next_token], "%s", farg) > 0)
          ++fnum;

      if (fnum > 0)
        {
          if (!strcmp(fopt, "help"))
            {
              if (override || !args_info->help_given)
                {
                  args_info->help_given = 1;
                  
                }
              continue;
            }
          if (!strcmp(fopt, "version"))
            {
              if (override || !args_info->version_given)
                {
                  args_info->version_given = 1;
                  
                }
              continue;
            }
          if (!strcmp(fopt, "config"))
            {
              if (override || !args_info->config_given)
                {
                  args_info->config_given = 1;
                  if (fnum == 2)
                    {
                      args_info->config_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "sky-grid"))
            {
              if (override || !args_info->sky_grid_given)
                {
                  args_info->sky_grid_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->sky_grid_arg)
                        free (args_info->sky_grid_arg); /* free default string */
                      args_info->sky_grid_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "skymap-orientation"))
            {
              if (override || !args_info->skymap_orientation_given)
                {
                  args_info->skymap_orientation_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->skymap_orientation_arg)
                        free (args_info->skymap_orientation_arg); /* free default string */
                      args_info->skymap_orientation_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fine-factor"))
            {
              if (override || !args_info->fine_factor_given)
                {
                  args_info->fine_factor_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fine_factor_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "resolution-ratio"))
            {
              if (override || !args_info->resolution_ratio_given)
                {
                  args_info->resolution_ratio_given = 1;
                  if (fnum == 2)
                    {
                      args_info->resolution_ratio_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "small-weight-ratio"))
            {
              if (override || !args_info->small_weight_ratio_given)
                {
                  args_info->small_weight_ratio_given = 1;
                  if (fnum == 2)
                    {
                      args_info->small_weight_ratio_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "input"))
            {
              if (override || !args_info->input_given)
                {
                  args_info->input_given = 1;
                  if (fnum == 2)
                    {
                      args_info->input_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "input-munch"))
            {
              if (override || !args_info->input_munch_given)
                {
                  args_info->input_munch_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->input_munch_arg)
                        free (args_info->input_munch_arg); /* free default string */
                      args_info->input_munch_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "input-format"))
            {
              if (override || !args_info->input_format_given)
                {
                  args_info->input_format_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->input_format_arg)
                        free (args_info->input_format_arg); /* free default string */
                      args_info->input_format_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "segments-file"))
            {
              if (override || !args_info->segments_file_given)
                {
                  args_info->segments_file_given = 1;
                  if (fnum == 2)
                    {
                      args_info->segments_file_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "veto-segments-file"))
            {
              if (override || !args_info->veto_segments_file_given)
                {
                  args_info->veto_segments_file_given = 1;
                  if (fnum == 2)
                    {
                      args_info->veto_segments_file_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "output"))
            {
              if (override || !args_info->output_given)
                {
                  args_info->output_given = 1;
                  if (fnum == 2)
                    {
                      args_info->output_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "ephemeris-path"))
            {
              if (override || !args_info->ephemeris_path_given)
                {
                  args_info->ephemeris_path_given = 1;
                  if (fnum == 2)
                    {
                      args_info->ephemeris_path_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "earth-ephemeris"))
            {
              if (override || !args_info->earth_ephemeris_given)
                {
                  args_info->earth_ephemeris_given = 1;
                  if (fnum == 2)
                    {
                      args_info->earth_ephemeris_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "sun-ephemeris"))
            {
              if (override || !args_info->sun_ephemeris_given)
                {
                  args_info->sun_ephemeris_given = 1;
                  if (fnum == 2)
                    {
                      args_info->sun_ephemeris_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "first-bin"))
            {
              if (override || !args_info->first_bin_given)
                {
                  args_info->first_bin_given = 1;
                  if (fnum == 2)
                    {
                      args_info->first_bin_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "nbins"))
            {
              if (override || !args_info->nbins_given)
                {
                  args_info->nbins_given = 1;
                  if (fnum == 2)
                    {
                      args_info->nbins_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "side-cut"))
            {
              if (override || !args_info->side_cut_given)
                {
                  args_info->side_cut_given = 1;
                  if (fnum == 2)
                    {
                      args_info->side_cut_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "detector"))
            {
              if (override || !args_info->detector_given)
                {
                  args_info->detector_given = 1;
                  if (fnum == 2)
                    {
                      args_info->detector_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "spindown"))
            {
              if (override || !args_info->spindown_given)
                {
                  args_info->spindown_given = 1;
                  if (fnum == 2)
                    {
                      args_info->spindown_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "orientation"))
            {
              if (override || !args_info->orientation_given)
                {
                  args_info->orientation_given = 1;
                  if (fnum == 2)
                    {
                      args_info->orientation_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "npolarizations"))
            {
              if (override || !args_info->npolarizations_given)
                {
                  args_info->npolarizations_given = 1;
                  if (fnum == 2)
                    {
                      args_info->npolarizations_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "no-demodulation"))
            {
              if (override || !args_info->no_demodulation_given)
                {
                  args_info->no_demodulation_given = 1;
                  if (fnum == 2)
                    {
                      args_info->no_demodulation_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "no-decomposition"))
            {
              if (override || !args_info->no_decomposition_given)
                {
                  args_info->no_decomposition_given = 1;
                  if (fnum == 2)
                    {
                      args_info->no_decomposition_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "no-am-response"))
            {
              if (override || !args_info->no_am_response_given)
                {
                  args_info->no_am_response_given = 1;
                  if (fnum == 2)
                    {
                      args_info->no_am_response_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "three-bins"))
            {
              if (override || !args_info->three_bins_given)
                {
                  args_info->three_bins_given = 1;
                  if (fnum == 2)
                    {
                      args_info->three_bins_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "do-cutoff"))
            {
              if (override || !args_info->do_cutoff_given)
                {
                  args_info->do_cutoff_given = 1;
                  if (fnum == 2)
                    {
                      args_info->do_cutoff_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "filter-lines"))
            {
              if (override || !args_info->filter_lines_given)
                {
                  args_info->filter_lines_given = 1;
                  if (fnum == 2)
                    {
                      args_info->filter_lines_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "nbands"))
            {
              if (override || !args_info->nbands_given)
                {
                  args_info->nbands_given = 1;
                  if (fnum == 2)
                    {
                      args_info->nbands_arg = strtol (farg,&stop_char,0);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "band-axis"))
            {
              if (override || !args_info->band_axis_given)
                {
                  args_info->band_axis_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->band_axis_arg)
                        free (args_info->band_axis_arg); /* free default string */
                      args_info->band_axis_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-ra"))
            {
              if (override || !args_info->fake_ra_given)
                {
                  args_info->fake_ra_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_ra_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-dec"))
            {
              if (override || !args_info->fake_dec_given)
                {
                  args_info->fake_dec_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_dec_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-orientation"))
            {
              if (override || !args_info->fake_orientation_given)
                {
                  args_info->fake_orientation_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_orientation_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-spindown"))
            {
              if (override || !args_info->fake_spindown_given)
                {
                  args_info->fake_spindown_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_spindown_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-strain"))
            {
              if (override || !args_info->fake_strain_given)
                {
                  args_info->fake_strain_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_strain_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "fake-freq"))
            {
              if (override || !args_info->fake_freq_given)
                {
                  args_info->fake_freq_given = 1;
                  if (fnum == 2)
                    {
                      args_info->fake_freq_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "write-dat"))
            {
              if (override || !args_info->write_dat_given)
                {
                  args_info->write_dat_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->write_dat_arg)
                        free (args_info->write_dat_arg); /* free default string */
                      args_info->write_dat_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "write-png"))
            {
              if (override || !args_info->write_png_given)
                {
                  args_info->write_png_given = 1;
                  if (fnum == 2)
                    {
                      if (args_info->write_png_arg)
                        free (args_info->write_png_arg); /* free default string */
                      args_info->write_png_arg = gengetopt_strdup (farg);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "focus-ra"))
            {
              if (override || !args_info->focus_ra_given)
                {
                  args_info->focus_ra_given = 1;
                  if (fnum == 2)
                    {
                      args_info->focus_ra_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "focus-dec"))
            {
              if (override || !args_info->focus_dec_given)
                {
                  args_info->focus_dec_given = 1;
                  if (fnum == 2)
                    {
                      args_info->focus_dec_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "focus-radius"))
            {
              if (override || !args_info->focus_radius_given)
                {
                  args_info->focus_radius_given = 1;
                  if (fnum == 2)
                    {
                      args_info->focus_radius_arg = strtod (farg, NULL);
                    }
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          

          /* Tried all known options. This one is unknown! */
          fprintf (stderr, "%s: Unknown option '%s' found in %s\n",
                   CMDLINE_PARSER_PACKAGE, fopt, filename);
          exit (EXIT_FAILURE);
        }
    } /* while */
  fclose(file); /* No error checking on close */

  return 0;
}
