#line 2 "make_sft_op_conf.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
static yyconst short int yy_accept[614] =
    {   0,
       41,   41,   44,   41,   41,   42,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   42,   41,    1,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,    4,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   27,   41,
       17,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   26,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   10,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,    2,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   24,   41,   41,   41,   41,

       41,   41,   39,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   11,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   21,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   22,   41,
       41,   41,   41,    9,   41,   41,   20,   41,   41,    6,
       41,   41,   41,   41,   41,   15,   41,   41,   41,   41,
       41,   18,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    7,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   25,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,    8,   41,
       41,   41,    5,   41,   41,   41,   33,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   14,   41,   41,   41,   41,   30,
       41,   41,   34,   41,   41,   41,   41,   41,   13,   41,
       23,   41,   16,   41,   41,   41,   41,   32,   41,   41,
       41,   41,   41,   41,   41,   12,   41,   41,   41,   41,
       31,   41,   41,   41,   41,   41,   41,   41,   41,    3,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   40,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       28,   41,   41,   35,   41,   41,   37,   41,   19,   41,
       41,   41,   41,   41,   41,   36,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   29,   41,   41,   41,   41,
       41,   38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    6,    6,    1,    7,    8,    9,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,   29,   30,   31,   32,   33,
        1,    1,    1,    1,   34,    1,    1,    1,    1,    1,

        6,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[626] =
    {   0,
        0,    0,  958,    0,   33,  959,  954,  936,  923,   20,
       24,   30,  936,  930,  924,  926,  916,   29,  924,  930,
        0,   39,  959,  944,  959,  922,  921,  934,  928,  931,
      919,  915,  920,  928,  921,  906,  908,  920,  918,  911,
      915,  920,  918,  918,  905,  909,  915,  902,  905,  894,
      894,  910,  905,  897,  900,  892,  891,  902,  895,  888,
      890,  885,  883,  896,  894,  896,  879,  882,  883,  886,
      867,  873,  865,  884,  873,  886,  867,  876,  873,  872,
      877,  863,  875,  874,  864,  852,  859,  870,  869,   37,
      867,  863,  867,  845,  868,  851,  849,  849,  860,  859,

      850,  837,  858,  835,  838,  856,  832,  845,  862,   51,
      833,  852,  838,  850,  844,  832,  831,  822,  837,  852,
       35,  826,  826,  828,   38,   40,  836,   48,  847,   62,
       68,  830,  829,  824,  818,  826,  817,  808,   62,  818,
       73,  806,  813,  812,  810,  814,  825,  811,  799,  805,
      813,  812,  806,   74,  824,  823,  804,  805,  822,  813,
      802,  787,  805,  809,  808,  794,  793,  800,  792,  809,
      788,  797,   77,  787,  796,  788,  777,  779,  795,  779,
      787,  772,  797,  796,   87,  795,   90,  785,  763,   93,
      762,  781,  779,  775,  770,  771,  777,  759,  761,  785,

      782,   94,  771,  768,   79,  959,  759,  748,  763,  766,
       74,  745,  752,  760,  752,  771,  101,  105,  959,  108,
      959,  751,  750,  111,  102,  746,  753,  750,  756,  750,
      753,  752,  763,  114,  122,  959,  739,  742,  728,  735,
      749,  734,  740,  733,  741,  728,  730,  743,  127,  959,
      722,  729,  130,  123,  740,  731,  132,  728,  720,   65,
      735,  711,  719,   83,  140,  709,  728,  726,  726,  714,
      138,  718,  723,  718,  701,  724,  707,  136,  698,  148,
      711,  708,  707,  706,  150,  959,  700,  712,  156,  714,
      699,  150,  721,  718,  157,  959,  695,  698,  694,  702,

      707,  165,  959,  682,  713,  694,  683,  686,  685,  708,
      148,  169,  959,  691,  682,  694,  692,  691,  679,  180,
      685,  692,  683,  686,  685,  113,  694,  171,  683,  669,
      685,  673,  666,  666,  174,  677,  672,  663,  654,  181,
      669,  672,  674,  657,  660,  648,  656,  678,  193,  657,
      651,  655,  653,  644,  670,  188,  959,  661,  646,  650,
      656,  651,  650,  663,  664,  643,  630,  648,  658,  635,
      635,  634,  648,  636,  626,  653,  196,  206,  628,  639,
      642,  177,  624,  646,  214,  626,  194,  634,  625,  623,
      612,  640,  219,  222,  630,  627,  623,  636,  225,  613,

      615,  627,  614,  601,  624,  223,  231,  208,  959,  631,
      619,  606,  232,  959,  234,  239,  959,  608,  242,  959,
      595,  601,  605,  612,  244,  959,  621,  601,  605,  602,
      247,  959,  603,  586,  592,  591,  601,  587,  250,  258,
      254,  581,  579,  251,  959,  597,  594,  582,  569,  600,
      594,  266,  567,  576,  568,  568,  576,  574,  253,  575,
      570,  286,  299,  269,  570,  271,  580,  559,  277,  552,
      282,  279,  959,  283,  548,  558,  555,  544,  556,  312,
      549,  535,  560,  325,  338,  295,  549,  296,  959,  308,
      538,  309,  959,  534,  321,  333,  959,  542,  526,  516,

      335,  515,  351,  528,  519,  364,  377,  390,  360,  517,
      373,  529,  508,  339,  959,  512,  346,  338,  353,  959,
      510,  372,  959,  513,  506,  403,  416,  385,  959,  387,
      959,  521,  959,  504,  511,  392,  398,  959,  514,  510,
      501,  498,  499,  429,  400,  959,  510,  404,  486,  411,
      959,  490,  480,  484,  503,  494,  442,  424,  413,  959,
      418,  481,  488,  480,  455,  471,  468,  488,  430,  959,
      480,  437,  452,  481,  483,  494,  477,  443,  455,  439,
      959,  443,  450,  959,  507,  452,  959,  456,  959,  424,
      419,  520,  400,  379,  463,  959,  359,  350,  338,  341,

      303,  533,  465,  546,  469,  959,  559,  572,  585,  598,
      476,  959,  959,  321,  612,  308,  295,  274,  218,  205,
      192,  183,  153,  135,   50
    } ;

static yyconst short int yy_def[626] =
    {   0,
      613,    1,  613,  614,  614,  613,  615,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  613,  615,  613,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  616,  617,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  618,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  619,  616,  616,  617,  617,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      618,  618,  614,  614,  614,  613,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  619,  619,  616,  613,  617,
      613,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  618,  613,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  619,  613,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  613,  614,  614,  614,  614,
      614,  614,  614,  620,  614,  613,  614,  614,  614,  614,

      614,  614,  613,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  613,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  620,  620,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  621,  620,  613,  614,  614,  614,
      614,  614,  614,  622,  614,  614,  614,  614,  623,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  621,  621,  614,  614,  614,  614,  614,
      614,  622,  622,  614,  614,  614,  614,  623,  623,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  613,  614,
      614,  614,  614,  613,  614,  621,  613,  614,  614,  613,
      614,  614,  614,  614,  622,  613,  624,  614,  614,  614,
      623,  613,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  613,  614,  614,  614,  614,  614,
      624,  624,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  624,  613,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  613,  614,
      614,  614,  613,  614,  614,  614,  613,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  613,  614,  614,  614,  614,  613,
      614,  614,  613,  614,  614,  614,  614,  614,  613,  614,
      613,  614,  613,  614,  614,  614,  614,  613,  614,  614,
      614,  614,  614,  614,  614,  613,  614,  614,  614,  614,
      613,  614,  614,  614,  614,  614,  614,  614,  614,  613,
      614,  614,  614,  614,  614,  614,  614,  625,  614,  613,
      614,  614,  614,  614,  614,  614,  625,  625,  614,  614,
      613,  614,  614,  613,  614,  614,  613,  625,  613,  614,
      614,  614,  614,  614,  614,  613,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  613,  614,  614,  614,  614,
      614,  613,    0,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613
    } ;

static yyconst short int yy_nxt[994] =
    {   0,
        4,    5,    6,    4,    7,    4,    4,    4,    4,    8,
        9,   10,   11,    4,   12,    4,   13,    4,    4,   14,
        4,    4,   15,   16,   17,   18,   19,    4,    4,   20,
        4,    4,    4,    4,   22,   23,   28,   30,   40,   33,
       22,   23,   41,  110,  110,  110,   31,  149,  149,  147,
      577,   32,  131,   29,   34,   42,   43,  110,  110,  110,
      142,  148,  151,  130,  152,  155,  289,  153,  143,  131,
      111,  156,  164,  165,  141,  154,  170,  183,  205,  206,
      205,  206,  166,  243,  264,  167,  294,  168,  218,  219,
      185,  220,  221,  187,  190,  235,  236,  202,  290,  224,

      224,  224,  249,  250,  217,  244,  218,  219,  185,  220,
      221,  187,  253,  254,  326,  234,  355,  224,  224,  224,
      265,  265,  265,  235,  236,  202,  255,  256,  249,  250,
      217,  253,  281,  285,  286,  451,  280,  280,  280,  302,
      303,  295,  296,  310,  310,  282,  265,  265,  265,  312,
      313,  285,  286,  398,  280,  280,  280,  289,  295,  296,
      323,  320,  320,  320,  320,  324,  302,  303,  341,  320,
      312,  313,  356,  357,  328,  335,  325,  364,  413,  414,
      342,  349,  340,  392,  369,  320,  320,  320,  320,  356,
      357,  328,  384,  320,  349,  419,  420,  377,  378,  378,

      378,  378,  407,  407,  407,  327,  378,  408,  409,  408,
      409,  378,  378,  378,  378,  416,  417,  385,  216,  378,
      425,  426,  393,  394,  406,  427,  431,  432,  399,  439,
      439,  439,  440,  413,  414,  444,  445,  407,  407,  407,
      416,  417,  385,  419,  420,  425,  426,  393,  431,  432,
      399,  462,  444,  445,  480,  441,  439,  439,  439,  440,
      464,  464,  464,  463,  463,  463,  463,  472,  473,  452,
      486,  463,  488,  489,  201,  464,  464,  464,  492,  493,
      472,  473,  452,  471,  496,  497,  481,  462,  495,  495,
      495,  484,  484,  484,  484,  186,  486,  488,  489,  484,

      485,  509,  509,  509,  463,  463,  463,  463,  184,  490,
      492,  493,  463,  480,  511,  511,  511,  503,  503,  503,
      503,   21,  514,  515,  603,  503,  507,  495,  495,  495,
      484,  484,  484,  484,  496,  497,  519,  520,  484,  485,
      514,  515,  602,  508,  508,  508,  508,  537,  538,  539,
      540,  508,  522,  523,  519,  520,  503,  503,  503,  503,
      601,  530,  531,  600,  503,  506,  509,  509,  509,  526,
      526,  526,  526,  522,  523,  533,  599,  526,  507,  511,
      511,  511,  527,  527,  527,  527,  528,  529,  530,  531,
      527,  528,  529,  550,  551,  508,  508,  508,  508,  537,

      538,  545,  546,  508,  544,  559,  560,  598,  526,  526,
      526,  526,  550,  551,  559,  560,  526,  545,  546,  569,
      570,  527,  527,  527,  527,  558,  597,  568,  594,  527,
      544,  569,  570,  593,  557,  557,  557,  557,  580,  581,
      580,  581,  557,  567,  588,  589,  578,  557,  557,  557,
      557,  583,  584,  586,  587,  557,  565,  588,  589,  578,
      574,  574,  574,  574,  595,  596,  605,  606,  574,  567,
      605,  606,  591,  576,  576,  576,  576,  611,  612,  590,
      578,  576,  583,  584,  585,  582,  574,  574,  574,  574,
      579,  578,  575,  573,  574,  586,  587,  572,  571,  576,

      576,  576,  576,  566,  565,  564,  563,  576,  585,  562,
      561,  558,  592,  592,  592,  592,  556,  555,  554,  553,
      592,  595,  596,  552,  549,  592,  592,  592,  592,  548,
      547,  543,  542,  592,  602,  541,  536,  535,  604,  604,
      604,  604,  534,  532,  525,  524,  604,  607,  521,  518,
      517,  604,  604,  604,  604,  516,  513,  512,  510,  604,
      607,  506,  505,  504,  608,  608,  608,  608,  502,  501,
      500,  499,  608,  609,  498,  494,  491,  608,  608,  608,
      608,  490,  487,  483,  482,  608,  609,  479,  478,  477,
      610,  610,  610,  610,  476,  475,  474,  452,  610,  611,

      612,  471,  470,  610,  610,  610,  610,  469,  468,  467,
      466,  610,   24,   24,  465,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  450,  449,  448,  447,  446,
      443,  442,  441,  438,  437,  436,  435,  434,  433,  399,
      430,  429,  428,  393,  424,  423,  422,  421,  418,  385,
      415,  412,  411,  410,  406,  405,  404,  403,  402,  401,
      400,  399,  397,  396,  395,  394,  393,  391,  390,  389,
      388,  387,  386,  385,  383,  382,  381,  380,  379,  377,
      376,  375,  374,  373,  372,  371,  370,  368,  367,  366,
      365,  363,  362,  361,  360,  359,  358,  328,  354,  353,

      352,  351,  350,  348,  347,  346,  345,  344,  343,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  326,  322,  321,  319,  318,  317,  316,  315,
      314,  311,  309,  308,  307,  306,  305,  304,  301,  300,
      299,  298,  297,  293,  292,  291,  288,  287,  284,  283,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  264,  263,  262,  261,  260,  259,
      258,  257,  252,  251,  217,  248,  247,  246,  245,  242,
      241,  240,  239,  238,  237,  202,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  223,  222,  187,  185,

      217,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      204,  203,  202,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  185,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      169,  163,  162,  161,  160,  159,  158,  157,  154,  150,
      146,  145,  144,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  109,  108,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,

       91,   90,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       51,   50,   49,   48,   47,   46,   25,   45,   44,   39,
       38,   37,   36,   35,   27,   26,   25,  613,    3,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613

    } ;

static yyconst short int yy_chk[994] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,   10,   11,   18,   12,
       22,   22,   18,   90,   90,   90,   11,  126,  126,  125,
      625,   11,  110,   10,   12,   18,   18,  110,  110,  110,
      121,  125,  128,  130,  128,  130,  260,  128,  121,  131,
       90,  131,  139,  139,  141,  154,  141,  154,  173,  173,
      205,  205,  139,  211,  264,  139,  264,  139,  185,  185,
      185,  187,  187,  187,  190,  202,  202,  202,  260,  190,

      190,  190,  217,  217,  217,  211,  218,  218,  218,  220,
      220,  220,  224,  225,  326,  234,  326,  224,  224,  224,
      234,  234,  234,  235,  235,  235,  225,  225,  249,  249,
      249,  253,  254,  257,  257,  624,  253,  253,  253,  271,
      271,  265,  265,  278,  278,  254,  265,  265,  265,  280,
      280,  285,  285,  623,  280,  280,  280,  289,  295,  295,
      292,  289,  289,  289,  289,  292,  302,  302,  311,  289,
      312,  312,  328,  328,  328,  335,  292,  335,  382,  382,
      311,  320,  340,  622,  340,  320,  320,  320,  320,  356,
      356,  356,  621,  320,  349,  387,  387,  377,  349,  349,

      349,  349,  377,  377,  377,  620,  349,  378,  378,  408,
      408,  378,  378,  378,  378,  385,  385,  385,  619,  378,
      393,  393,  393,  394,  406,  394,  399,  399,  399,  406,
      406,  406,  407,  413,  413,  415,  415,  407,  407,  407,
      416,  416,  416,  419,  419,  425,  425,  425,  431,  431,
      431,  439,  444,  444,  459,  441,  439,  439,  439,  440,
      441,  441,  441,  440,  440,  440,  440,  452,  452,  452,
      464,  440,  466,  466,  618,  464,  464,  464,  469,  469,
      472,  472,  472,  471,  474,  474,  459,  462,  471,  471,
      471,  462,  462,  462,  462,  617,  486,  488,  488,  462,

      463,  486,  486,  486,  463,  463,  463,  463,  616,  490,
      492,  492,  463,  480,  490,  490,  490,  480,  480,  480,
      480,  614,  495,  495,  601,  480,  484,  495,  495,  495,
      484,  484,  484,  484,  496,  496,  501,  501,  484,  485,
      514,  514,  600,  485,  485,  485,  485,  517,  517,  518,
      518,  485,  503,  503,  519,  519,  503,  503,  503,  503,
      599,  509,  509,  598,  503,  506,  509,  509,  509,  506,
      506,  506,  506,  522,  522,  511,  597,  506,  507,  511,
      511,  511,  507,  507,  507,  507,  528,  528,  530,  530,
      507,  508,  508,  536,  536,  508,  508,  508,  508,  537,

      537,  545,  545,  508,  526,  548,  548,  594,  526,  526,
      526,  526,  550,  550,  559,  559,  526,  527,  527,  561,
      561,  527,  527,  527,  527,  558,  593,  558,  591,  527,
      544,  569,  569,  590,  544,  544,  544,  544,  572,  572,
      580,  580,  544,  557,  578,  578,  578,  557,  557,  557,
      557,  583,  583,  586,  586,  557,  565,  588,  588,  588,
      565,  565,  565,  565,  595,  595,  603,  603,  565,  567,
      605,  605,  582,  567,  567,  567,  567,  611,  611,  579,
      577,  567,  574,  574,  575,  573,  574,  574,  574,  574,
      571,  568,  566,  564,  574,  576,  576,  563,  562,  576,

      576,  576,  576,  556,  555,  554,  553,  576,  585,  552,
      549,  547,  585,  585,  585,  585,  543,  542,  541,  540,
      585,  592,  592,  539,  535,  592,  592,  592,  592,  534,
      532,  525,  524,  592,  602,  521,  516,  513,  602,  602,
      602,  602,  512,  510,  505,  504,  602,  604,  502,  500,
      499,  604,  604,  604,  604,  498,  494,  491,  487,  604,
      607,  483,  482,  481,  607,  607,  607,  607,  479,  478,
      477,  476,  607,  608,  475,  470,  468,  608,  608,  608,
      608,  467,  465,  461,  460,  608,  609,  458,  457,  456,
      609,  609,  609,  609,  455,  454,  453,  451,  609,  610,

      610,  450,  449,  610,  610,  610,  610,  448,  447,  446,
      443,  610,  615,  615,  442,  438,  437,  436,  435,  434,
      433,  430,  429,  428,  427,  424,  423,  422,  421,  418,
      412,  411,  410,  405,  404,  403,  402,  401,  400,  398,
      397,  396,  395,  392,  391,  390,  389,  388,  386,  384,
      383,  381,  380,  379,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  355,  354,  353,  352,  351,  350,  348,
      347,  346,  345,  344,  343,  342,  341,  339,  338,  337,
      336,  334,  333,  332,  331,  330,  329,  327,  325,  324,

      323,  322,  321,  319,  318,  317,  316,  315,  314,  310,
      309,  308,  307,  306,  305,  304,  301,  300,  299,  298,
      297,  294,  293,  291,  290,  288,  287,  284,  283,  282,
      281,  279,  277,  276,  275,  274,  273,  272,  270,  269,
      268,  267,  266,  263,  262,  261,  259,  258,  256,  255,
      252,  251,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  233,  232,  231,  230,  229,  228,
      227,  226,  223,  222,  216,  215,  214,  213,  212,  210,
      209,  208,  207,  204,  203,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  189,  188,  186,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      140,  138,  137,  136,  135,  134,  133,  132,  129,  127,
      124,  123,  122,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,

       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       51,   50,   49,   48,   47,   46,   45,   44,   43,   42,
       41,   40,   39,   38,   37,   36,   35,   34,   33,   32,
       31,   30,   29,   28,   27,   26,   24,   20,   19,   17,
       16,   15,   14,   13,    9,    8,    7,    3,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "make_sft_op_conf.l"
#define INITIAL 0
#line 9 "make_sft_op_conf.l"

#include "make_sft_global.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

extern INT64 gps_start, gps_end;
extern long samples_per_second;

int mode;

extern int output_mode;
extern int precision;
extern long freq_start, freq_stop;
extern long overlap;
extern char *output_calibrated_data;
extern char *output_power;
extern char *output_sft;

extern char bypass_highpass_filter, bypass_lowpass_filter, bypass_first_window;
	
extern REAL4 highpass_filter_f, highpass_filter_a, lowpass_filter_f, lowpass_filter_a;
extern int highpass_filter_order, lowpass_filter_order;

extern MAKE_SFT_WINDOW window1, window2;

extern char trace_power, trace_calibration_power;

extern char *channel;

#define MODE_NONE			0
#define MODE_FRAME_FILES		1
#define MODE_SEGMENTS			2
#define MODE_SUBSECOND_SEGMENTS 	3
#define MODE_SAMPLE_SEGMENTS		4
#define MODE_START_STOP_FRAME_FILES	5

double conf_a, conf_b, conf_c;
long conf_i;
unsigned char *conf_p=NULL;

int dont_fail_on_missing_data=0, dont_fail_on_missing_calibration=0, dont_fail_on_zero_ds=0;


#line 836 "make_sft_op_conf.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 55 "make_sft_op_conf.l"


#line 990 "make_sft_op_conf.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 614 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 959 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "make_sft_op_conf.l"
{ /* ignore comments */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "make_sft_op_conf.l"
{ mode=MODE_FRAME_FILES; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "make_sft_op_conf.l"
{ mode=MODE_START_STOP_FRAME_FILES; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "make_sft_op_conf.l"
{ mode=MODE_SEGMENTS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "make_sft_op_conf.l"
{ mode=MODE_SUBSECOND_SEGMENTS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "make_sft_op_conf.l"
{ mode=MODE_SAMPLE_SEGMENTS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "make_sft_op_conf.l"
{
	output_mode=OUTPUT_MODE_TEXT;
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "make_sft_op_conf.l"
{
	output_mode=OUTPUT_MODE_BINARY;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "make_sft_op_conf.l"
{
	output_mode=OUTPUT_MODE_GEO;
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "make_sft_op_conf.l"
{
	if(channel!=NULL)free(channel);
	channel=dup_quoted_name(yytext);
	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "make_sft_op_conf.l"
{
	sscanf(yytext+8,"%lld %lld", &gps_start, &gps_end);
	allocate_data();
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "make_sft_op_conf.l"
{
	sscanf(yytext+15,"%d %g %g", &highpass_filter_order, &highpass_filter_f, &highpass_filter_a);
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "make_sft_op_conf.l"
{
	sscanf(yytext+14,"%d %g %g", &lowpass_filter_order, &lowpass_filter_f, &lowpass_filter_a);
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "make_sft_op_conf.l"
{
	sscanf(yytext+17, "%ld", &conf_i);
	if(conf_i<0){
		fprintf(stderr, "** Window %c tail size must be non-negative\n", yytext[6]);
		exit(-1);
		}
	if(samples_per_second<0){
		fprintf(stderr, "** WINDOW%c_TAIL_SIZE must follow valid SAMPLES_PER_SECOND command\n", yytext[6]);
		exit(-1);
		}
	if(conf_i>30*samples_per_second){
		fprintf(stderr, "** Window tail size is too big\n");
		exit(-1);
		}
	switch(yytext[6]){
		case '1':
			window1.tail_size=conf_i;	
			break;
		case '2':
			window2.tail_size=conf_i;	
			break;
		default:
			fprintf(stderr, "** INTERNAL ERROR - window tail size specification (%c)\n", yytext[6]);
			exit(-1);
		}
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "make_sft_op_conf.l"
{
	switch(yytext[6]){
		case '1':
			window1.type=translate_window_type(yytext+12);	
			break;
		case '2':
			window2.type=translate_window_type(yytext+12);	
			break;
		default:
			fprintf(stderr, "** INTERNAL ERROR - window type specification (%c)\n", yytext[6]);
			exit(-1);
		}
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "make_sft_op_conf.l"
{
	sscanf(yytext+18, "%ld", &samples_per_second);
	allocate_data();
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "make_sft_op_conf.l"
{
	set_debug_output(yytext);
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "make_sft_op_conf.l"
{
	{ MAKE_SFT_WINDOW *w;
		switch(yytext[12]){
			case '1':
				w=&window1;
				break;
			case '2':
				w=&window2;
				break;
			default:
				fprintf(stderr, "** INTERNAL ERROR - window debug specification (%c)\n", yytext[12]);
				exit(-1);
			}
		if(w->debug!=NULL)free(w->debug);
		w->debug=dup_quoted_name(yytext+13);
		}
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "make_sft_op_conf.l"
{
	if(output_calibrated_data!=NULL)free(output_calibrated_data);
	output_calibrated_data=dup_quoted_name(yytext+23);
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 172 "make_sft_op_conf.l"
{
	if(output_power!=NULL)free(output_power);
	output_power=dup_quoted_name(yytext+12);
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 176 "make_sft_op_conf.l"
{
	if(output_sft!=NULL)free(output_sft);
	output_sft=dup_quoted_name(yytext+10);
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 181 "make_sft_op_conf.l"
{
	if((gps_start<0)||(gps_end<0)){
		fprintf(stderr,"** OUTPUT_BAND command must follow DURATION command\n");
		exit(-1);
		}
	sscanf(yytext+11,"%lg %lg", &conf_a, &conf_b);
	freq_start=lrint(conf_a*(gps_end-gps_start));
	freq_stop=lrint(conf_b*(gps_end-gps_start));
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 191 "make_sft_op_conf.l"
{
	sscanf(yytext+16, "%ld %ld", &freq_start, &freq_stop);
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 195 "make_sft_op_conf.l"
{
	sscanf(yytext+9, "%d", &precision);
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 199 "make_sft_op_conf.l"
{
	conf_p=dup_quoted_name(yytext+15);
	load_alpha_beta(conf_p);
	free(conf_p);
	conf_p=NULL;
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 206 "make_sft_op_conf.l"
{
	conf_p=dup_quoted_name(yytext+6);
	load_R(conf_p);
	free(conf_p);
	conf_p=NULL;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 213 "make_sft_op_conf.l"
{
	conf_p=dup_quoted_name(yytext+6);
	load_C(conf_p);
	free(conf_p);
	conf_p=NULL;
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 220 "make_sft_op_conf.l"
{
	dont_fail_on_missing_data=1;
	}	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 224 "make_sft_op_conf.l"
{
	dont_fail_on_missing_calibration=1;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 228 "make_sft_op_conf.l"
{
	dont_fail_on_zero_ds=1;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 232 "make_sft_op_conf.l"
{
	bypass_highpass_filter=1;
	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 236 "make_sft_op_conf.l"
{
	bypass_lowpass_filter=1;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 240 "make_sft_op_conf.l"
{
	bypass_first_window=1;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 244 "make_sft_op_conf.l"
{
	sscanf(yytext+18,"%lg", &conf_a);
	add_fake_data_command(FAKE_DATA_CONSTANT, 0.0, 0.0, conf_a);
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 249 "make_sft_op_conf.l"
{
	sscanf(yytext+23,"%lg", &conf_a);
	add_fake_data_command(FAKE_DATA_CONSTANT_FILL, 0.0, 0.0, conf_a);
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 254 "make_sft_op_conf.l"
{
	sscanf(yytext+18,"%lg", &conf_a);
	add_fake_data_command(FAKE_DATA_RANDOM_GAUSSIAN, 0.0, 0.0, conf_a);
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 259 "make_sft_op_conf.l"
{
	sscanf(yytext+19,"%lg %lg %lg", &conf_a, &conf_b, &conf_c);
	add_fake_data_command(FAKE_DATA_SINE_WAVE, (conf_a*M_PI)/180.0, conf_b, conf_c);
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 264 "make_sft_op_conf.l"
{
	sscanf(yytext+30,"%lg %lg %lg", &conf_a, &conf_b, &conf_c);
	add_fake_data_command(FAKE_DATA_CALIBRATED_SINE_WAVE, (conf_a*M_PI)/180.0, conf_b, conf_c);
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 269 "make_sft_op_conf.l"
{
	trace_power=1;
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 273 "make_sft_op_conf.l"
{
	trace_calibration_power=1;
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "make_sft_op_conf.l"
{
	switch(mode){
		case MODE_NONE:
			fprintf(stderr,"Could not parse line \"%s\"\n", yytext);
			break;
		case MODE_FRAME_FILES:
			add_frame_file(yytext, -1, -1);
			break;
		case MODE_START_STOP_FRAME_FILES:
			add_start_stop_frame_file(yytext);
			break;
		case MODE_SEGMENTS:
			assimilate_segment(yytext);
			break;
		case MODE_SUBSECOND_SEGMENTS:
			assimilate_subsecond_segment(yytext);
			break;
		case MODE_SAMPLE_SEGMENTS:
			assimilate_sample_segment(yytext);
			break;
		default:
			fprintf(stderr,"Unimplemented mode %d while parsing line \"%s\"\n", mode, yytext);
		}			
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 303 "make_sft_op_conf.l"
{
	/* skip whitespace and new lines */
	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 306 "make_sft_op_conf.l"
ECHO;
	YY_BREAK
#line 1454 "make_sft_op_conf.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 614 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 614 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 613);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 306 "make_sft_op_conf.l"

